CSVの項目、税金を削除
Best-Beer-Japan/ec-cube pull request #215
Opened 2023-07-11 20:39 UTC by belltzel

B2BEC-124

2023-07-13 05:27 UTC, yuk0ga requested changes

2023-07-13 05:27 UTC, yuk0ga commented on app/DoctrineMigrations/Version20230704223318.php
> +        $csvFieldTaxExist = $this->connection->fetchColumn("SELECT COUNT(*) FROM dtb_csv WHERE csv_type_id = 9 and field_name = 'tax'");
csv_type_id = 9 (e飛伝III CSV (ShippingSlip))にはもともと`tax`の項目なさそうです！
csv_type_id = 8（請求CSV）ですかね？
<img width="360" alt="image" src="https://github.com/Best-Beer-Japan/ec-cube/assets/24802707/402bea93-3f2f-493b-b2f2-ba2ba74db6aa">

2023-07-13 05:27 UTC, yuk0ga commented on app/DoctrineMigrations/Version20230704223318.php
> +        $csvFieldTaxExist = $this->connection->fetchColumn("SELECT COUNT(*) FROM dtb_csv WHERE csv_type_id = 9 and field_name = 'tax'");
<img width="461" alt="image" src="https://github.com/Best-Beer-Japan/ec-cube/assets/24802707/9b4b3bbc-3ae9-4364-83ef-a73d40cff5db">

2023-07-13 05:27 UTC, yuk0ga commented on app/DoctrineMigrations/Version20230704223318.php
> +        $sort_no = $this->connection->fetchColumn("SELECT max(sort_no) FROM dtb_csv WHERE csv_type_id = 9");
こちらも↑と同様

2023-07-13 05:36 UTC, belltzel commented on app/DoctrineMigrations/Version20230704223318.php
> +        $csvFieldTaxExist = $this->connection->fetchColumn("SELECT COUNT(*) FROM dtb_csv WHERE csv_type_id = 9 and field_name = 'tax'");
環境によってIDが違うのですね。。。

csv_type_idを固定ではなく、取得するように修正します。

2023-07-13 06:54 UTC, yuk0ga commented on app/DoctrineMigrations/Version20230704223318.php
> +        $csvFieldTaxExist = $this->connection->fetchColumn("SELECT COUNT(*) FROM dtb_csv WHERE csv_type_id = 9 and field_name = 'tax'");
たしかに環境によって違いますね・・ありがとうございます！

2023-10-18 07:42 UTC, yuk0ga approved these changes

2023-10-18 07:42 UTC, merged